src/OpenTracing.BasicTracer/LogData.cs, src/OpenTracing.BasicTracer/Span.cs, src/OpenTracing.BasicTracer/SpanBuilder.cs, src/OpenTracing.BasicTracer/SpanData.cs, src/OpenTracing.BasicTracer/Tracer.cs, src/OpenTracing/ISpan.cs, src/OpenTracing/ISpanBuilder.cs, src/OpenTracing/NullTracer/NullSpan.cs, src/OpenTracing/NullTracer/NullSpanBuilder.cs
As discussed in #4 we are using DateTime instead of DateTimeOffset for the following reasons:
* It doesn't automatically convert values with DateTimeKind.Local
* We can let trace implementations decide whether they want to convert non-UTC values.
* It's the most-known type for users
* It's a little bit faster
* We can switch to DateTimeOffset later without breaking consumers because there's an implicit cast. (we would only break trace implementations)
I added a recommendation about using `DateTimeKind.Utc` in the comments of each usage.
=> DateTime instead of DateTimeOffset; resolves #4

src/OpenTracing/Extensions/SpanTagExtensions.cs, src/OpenTracing/ISpan.cs, src/OpenTracing/Tags.cs
Renames to be closer to the Java version. Both names don't reflect common types in .NET so I think this should be fine and a bit more readable. `Field` from the Key-Value PR will also not contain a prefix.
I'll merge this if there are no complaints by Wednesday.
=> Naming: SpanTags->Tags

OpenTracing.sln, src/OpenTracing.BasicTracer/Propagation/TextMapCarrierHandler.cs, src/OpenTracing/Extensions/FormatBinaryExtensions.cs, src/OpenTracing/Extensions/FormatHttpHeadersExtensions.cs, src/OpenTracing/Propagation/DictionaryCarrier.cs, src/OpenTracing/Propagation/Format.cs, src/OpenTracing/Propagation/ITextMap.cs, src/OpenTracing/Propagation/SystemNetHttpHeadersCarrier.cs, test/OpenTracing.Tests/DictionaryCarrierTests.cs, test/OpenTracing.Tests/FormatTests.cs, test/OpenTracing.Tests/OpenTracing.Tests.xproj, test/OpenTracing.Tests/project.json
This PR does the following things:
* `Format` is now a struct instead of a class. Value comparison for structs is done by comparing each field so this is less code.
* Adds a new Test project with tests for `Format` equality and `DictionaryCarrier` behavior. It's a new project because the one for BasicTracer will be moved to the other repository.
* `ITextMap.Add` was renamed to `Set` because the Java equivalent `Put` means that keys are replaced if they already exist. `Set` is the common name in C# for this.
* Renames `HttpHeadersCarrier` to `SystemNetHttpHeadersCarrier`. This makes clear that this is not the base class but instead for one actual headers type. Users will usually not see this because they call the extension methods (which still have to be discussed in a separate issue)
=> Propagation improvements, Tests

src/OpenTracing/ISpan.cs, src/OpenTracing/ISpanBuilder.cs, src/OpenTracing/NullTracer/NullSpan.cs, src/OpenTracing/NullTracer/NullSpanBuilder.cs
I'm writing my first instrumentation for this library and I think, now that we no longer have extension methods on tags, it's way too easy to pass wrong types to `SetTag` and `WithTag`. Examples are passing enums instead of int, Uri instead of string, ...
This PR removes the string:object version and adds 3 overloads for `bool`/`string`/`double`. This is very similar to what Java has except that there isn't a base type for all numeric types in .NET. 
Using `double` will accept everything except `decimal`. If we would add an additional overload for `decimal`, then we have some types (e.g. `integer`) that would cast to both and the compiler will require an explicit cast. For this reason, I think it's ok to leave out decimal for now. If we need it, we probably need even more specific …
=> Restrict tag types to bool/double/string like in Java

src/OpenTracing/ISpan.cs, src/OpenTracing/Tags.cs
I've also sorted the tags and used the docs/examples from "semantic_conventions.md".
I'll immediately merge this since it should be a no-brainer.
=> Adds missing tags from specification

.travis.yml, build.sh
Fixes #38 
This is just a very simple bash build script. Note that it does NOT install the dotnet CLI. it must be installed according to https://www.microsoft.com/net/core
@TerribleDev Will this work for you?
=> Adds a (very) simple bash-based build-script

src/OpenTracing/LogFields.cs
This would add constants for the standard log fields from [semantic_conventions.md](https://github.com/opentracing/specification/blob/master/semantic_conventions.md)
A similar thing does not yet exist in Java though.
Also, I'm not sure if I should keep the `stack` field since it's probably never used by anyone. Instrumentation code will always just pass an exception object in `error.object` and the tracer will deal with it.
=> Adds constants for standard log fields

src/OpenTracing/ISpan.cs, src/OpenTracing/ISpanBuilder.cs, src/OpenTracing/NullTracer/NullSpan.cs, src/OpenTracing/NullTracer/NullSpanBuilder.cs
See #42. I'll merge this in 2-3 days if there's no voice against it.
This is non-breaking for users (since there is an implicit cast from DateTime to DateTimeOffset) but it will break tracers (at compile-time).
=> Replace DateTime usage with DateTimeOffset

src/OpenTracing/IScopeManager.cs, src/OpenTracing/ISpanBuilder.cs
Java has `Closable ` with a `close` method and .NET has `IDisposable` with a `Dispose` method.
To reduce confusion, I think it therefore makes sense to rename the parameter `finishSpanOnClose` to `finishSpanOnDispose`.
=> finishSpanOnDispose instead of finishSpanOnClose

build-definition.ps1, src/OpenTracing/OpenTracing.csproj, src/OpenTracing/Util/AsyncLocalScope.cs, src/OpenTracing/Util/AsyncLocalScopeManager.cs, test/OpenTracing.Tests/OpenTracing.Tests.csproj, test/OpenTracing.Tests/Util/AsyncLocalScopeManagerTests.cs, test/OpenTracing.Tests/Util/AsyncLocalScopeTests.cs
This is a port from opentracing-java's ThreadLocalScopeManager. 
* For storage it either uses `AsyncLocal` (.NET 4.6+, .NET Core) or the `CallContext` (.NET 4.5). This code is based on ASP.NET Core's [HttpContextAccessor](https://github.com/aspnet/HttpAbstractions/blob/622d112372ed11075af160b1fb5a11a7637ff516/src/Microsoft.AspNetCore.Http/HttpContextAccessor.cs).
* Since I had to fiddle around with #if-defs I'm now targeting `netstandard1.3` and `net452` as described in #62 - I'll change the targets here should that issue decide differently.
* The unit tests are also ported from Java.
* I also had to slightly change the build script (as the tests now target multiple frameworks) and I've updated the nuget dependencies.
* I have NOT ported Java's `AutoFinishScopeManager` as I'm not sure if …
=> AsyncLocal based scope manager (ported from Java)

src/OpenTracing/IScope.cs, src/OpenTracing/IScopeManager.cs, src/OpenTracing/ISpan.cs, src/OpenTracing/ISpanBuilder.cs, src/OpenTracing/ISpanContext.cs, src/OpenTracing/ITracer.cs, src/OpenTracing/LogFields.cs, src/OpenTracing/Mock/MockSpan.cs, src/OpenTracing/Mock/MockSpanContext.cs, src/OpenTracing/Mock/MockTracer.cs, src/OpenTracing/Propagation/BuiltinFormats.cs, src/OpenTracing/Propagation/IFormat.cs, src/OpenTracing/Propagation/ITextMap.cs, src/OpenTracing/Propagation/TextMapExtractAdapter.cs, src/OpenTracing/Propagation/TextMapInjectAdapter.cs, src/OpenTracing/References.cs, src/OpenTracing/Tag/Tags.cs, test/OpenTracing.Tests/Mock/MockTracerTests.cs, test/OpenTracing.Tests/Util/AsyncLocalScopeTests.cs
This PR only touches XML docs. It fixes typos, wrong code samples, inconsistent naming (e.g. Span vs span), missing punctuation and adds xml references where possible.
I'll merge this on Tuesday if there's no objections.
=> Improves XML docs (typos, wrong code samples, inconsistent naming, refs)

README.md
Better readme with an async/await example. It removes the reference to `basictracer-csharp` as that project doesn't contain code right now.
I will merge this on Monday or Tuesday if there's no objections.
=> Readme ported from Java with async/await example

src/OpenTracing/Mock/MockTracer.cs
Brings https://github.com/opentracing/opentracing-java/pull/264 to this repo.
As this has already been merged in Java, I'll immediately merge it here as well.
=> Updating MockTracer to use AsyncLocalScopeManager

src/OpenTracing/Noop/NoopScopeManager.cs, src/OpenTracing/Noop/NoopSpan.cs, src/OpenTracing/Noop/NoopSpanBuilder.cs, src/OpenTracing/Noop/NoopSpanContext.cs, src/OpenTracing/Noop/NoopTracer.cs
I want to be able to check if a given `ITracer` instance is a `NoopTracer`. My scenario is my [csharp-netcore](https://github.com/opentracing-contrib/csharp-netcore/issues/8) instrumentation library where I don't even want to start the instrumentation components if no tracer is registered. 
It's currently possible to do this via `if (tracer == NoopTracerFactory.Create()) { }` but that looks a bit weird IMO.
In opentracing-java the `Noop*` types are already public via interfaces - see e.g. [`NoopSpan`](https://github.com/opentracing/opentracing-java/blob/master/opentracing-noop/src/main/java/io/opentracing/noop/NoopSpan.java#L21). We haven't migrated these interface as it's not possible in C# to add the static `INSTANCE` variables to these interfaces.
So by making our types `public`, we …
=> Make NoopTracer types public

src/OpenTracing/IScopeManager.cs, src/OpenTracing/ISpan.cs, src/OpenTracing/ISpanBuilder.cs, src/OpenTracing/Mock/MockSpanBuilder.cs, src/OpenTracing/Noop/NoopSpanBuilder.cs
Resolves #73.
This is done by adding the method to the interface. I *think* this is better as it keeps everything in one place. We have to rely on tracers implementing this correctly but this shouldn't be a concern IMO (as they also have to implement all other behaviors correctly).
An alternative would be to add the method as an extension method. The advantage would be that it is non-breaking and that we could provide the implementation. However this would make the API a little bit more complex as methods would then be on interfaces and extension types. Also, NoopTracer could no longer immediately return (which probably is a negligible cost though).
Thoughts?
=> StartActive() overload with finishSpanOnDispose:true

src/OpenTracing/ISpan.cs, src/OpenTracing/ISpanBuilder.cs, src/OpenTracing/Mock/MockSpan.cs, src/OpenTracing/Mock/MockSpanBuilder.cs, src/OpenTracing/Noop/NoopSpan.cs, src/OpenTracing/Noop/NoopSpanBuilder.cs
I found the usage of `OpenTracing.Tag.Tags` somewhat inconvinient, since it was not usable with Fluent API.
=> Added SetTag and WithTag for use with OpenTracing.Tag.Tags

src/OpenTracing/Util/AsyncLocalScopeManager.cs, test/OpenTracing.Tests/Util/AsyncLocalScopeManagerTests.cs
Fixes #93. https://github.com/opentracing/opentracing-csharp/commit/aef788dda7b577ffce25714348076d5b0cdde0d0 demonstrates a test that fails before the change and passes after it.
**Problem:** Separate instances of `AsyncLocalScopeManager` will overwrite each other's data.
**Fix:** Use non-static `AsyncLocal` in the non-static `AsyncLocalScopeManager` class, and use `Guid` instead of `AppDomain.Id` for the pre4.6 implementation.
=> AsyncLocalScopeManager isolation

src/OpenTracing/ISpan.cs, src/OpenTracing/Mock/MockSpan.cs, src/OpenTracing/Noop/NoopSpan.cs
In v0.10.0 we used `Log(IEnumerable<KeyValuePair<string, object>> fields)`. With our big java parity-change in v0.11.0 we changed the signature to `Log(IDictionary<string, object> fields)`. This was an attempt to translate Java's `Map<K, V>` interface.
Java's `Map` interface does not implement any other interfaces. But in C# `IDictionary<K,V>` implements `ICollection<KeyValuePair<K, V>>` and `ICollection<T>` implements `IEnumerable<T>` so moving back to `IEnumerable<KeyValuePair<string, object>>` would be the most general type and a reasonable deviation from Java.
Using `IDictionary` does not give any guarantees regarding uniqueness anyway as people could call `Log()` with the same key multiple times or they could also use a non-unique implementation of `IDictionary`. This means that …
=> Use IEnumerable<KeyValuePair<string, object>> for Log() methods (again)

.appveyor.yml, Directory.Build.props, build.ps1, version.props
I'd like to do a RC-release with the upcoming changes. However, this is not possible with the current build script as it will always do a VersionSuffix-less release if there's a git tag.
With these changes, I introduced a separate version.props file that now contains all of the version number logic (similar to ASP.NET Core projects). I'm copying the description with the new logic from that file here for further details:
>These settings ensure that we don't have to manually increment version numbers after every release!
>
>If there's an AppVeyor tag, we always build with that tag name as the Version.
This overwrites any VersionPrefix and VersionSuffix so the tag MUST have a SemVer-compatible name!
>
>Any non-official (non-tagged) build uses a fixed (high) VersionPrefix and an incrementing …
=> Calculate version number based on environment/github tag

examples/OpenTracing.Examples/LateSpanFinish/LateSpanFinishTest.cs, src/OpenTracing/Propagation/BuiltinFormats.cs
This adds a builtin Binary Propagator format for consumers of the API.
=> Add a binary propagator format option

src/OpenTracing/ITracer.cs, src/OpenTracing/Mock/MockSpan.cs, src/OpenTracing/Mock/MockTracer.cs, src/OpenTracing/Mock/Propagators.cs, src/OpenTracing/Propagation/TextMapExtractAdapter.cs
I opened the repo with JetBrains Rider and it marked a couple of things in documentation comments with error.
Mainly 2 things:
- Missing generic parameter
- Missing namespace in `MockSpan.cs` without `using`
I think based on the specs those are correct and VS has no problem with it, still with this PR 1) Rider shows no errors anymore and 2) I see that the docs almost always use generic parameters, except in the cases this PR fixes, so this'd add consistency.
=> Fix minor documentation comment issues

src/OpenTracing/Util/GlobalTracer.cs, test/OpenTracing.Tests/Util/GlobalTracerTests.cs
Addresses #118 by wrapping `GlobalTracer.IsRegistered()` in a lock statement.
I've also implemented `GlobalTracer.RegisterIfAbsent(tracer)` that returns a bool to indicate if the registration was successful or not. This was copied from [opentracing-java](https://github.com/opentracing/opentracing-java/blob/master/opentracing-util/src/main/java/io/opentracing/util/GlobalTracer.java#L116).
=> Improve thread-safety in GlobalTracer.IsRegistered

src/OpenTracing/Mock/Propagators.cs, src/OpenTracing/Propagation/BinaryExtractAdapter.cs, src/OpenTracing/Propagation/BinaryInjectAdapter.cs, src/OpenTracing/Propagation/BuiltinFormats.cs, src/OpenTracing/Propagation/IBinary.cs
I've refactored the binary propagator to work like the TextMap propagator.
- Added `IBinary` interface which is implemented by `BinaryInjectAdapter` and `BinaryExtractAdapter`.
- `IBinary` offers a get and set method.
- `IBinary` is explicitly backed by a `MemoryStream`.
This is a bit different than the Java implementation, but we don't need to pass the length along like they do over there. This PR is mostly in support of adding support for decoding Envoy `x-ot-span-context` headers to OpenTracing tracers.
=> Improve Binary Propagator

.appveyor.yml
The existing GitHub token for creating releases no longer worked ( https://ci.appveyor.com/project/opentracing/opentracing-csharp/builds/26543348 ), I have therefore created a new personal access token in GitHub and I've updated the script to contain the AppVeyor-encrypted version of it.
I've tested this with a new tag (0.12.1-cwtest) and it worked ( https://ci.appveyor.com/project/opentracing/opentracing-csharp ). 
I've already deleted the corresponding tag and draft-release!
=> Updates GitHub token for creating releases
